package co.com.datacredito.services.serviciohistoriacreditoplus.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2019-12-09T18:06:19.064+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.datacredito.com.co/services/serviciohistoriacreditoplus/v1", name = "HC2PNJService")
@XmlSeeAlso({com.dc.hc2.ws.v1.ObjectFactory.class})
public interface HC2PNJService {

    @WebMethod
    @RequestWrapper(localName = "consultarHC2PJ", targetNamespace = "http://ws.hc2.dc.com/v1", className = "com.dc.hc2.ws.v1.HistoriaCreditoPlusPJ")
    @ResponseWrapper(localName = "consultarHC2PJResponse", targetNamespace = "http://ws.hc2.dc.com/v1", className = "com.dc.hc2.ws.v1.ConsultarHC2PJResponse")
    @WebResult(name = "consultarHC2PJReturn", targetNamespace = "http://ws.hc2.dc.com/v1")
    public java.lang.String consultarHC2PJ(
        @WebParam(name = "solicitud", targetNamespace = "http://ws.hc2.dc.com/v1")
        com.dc.hc2.ws.v1.SolicitudPlus solicitud
    ) throws HC2PNJException;

    @WebMethod
    @RequestWrapper(localName = "consultarHC2", targetNamespace = "http://ws.hc2.dc.com/v1", className = "com.dc.hc2.ws.v1.HistoriaCreditoPlus")
    @ResponseWrapper(localName = "consultarHC2Response", targetNamespace = "http://ws.hc2.dc.com/v1", className = "com.dc.hc2.ws.v1.ConsultarHC2Response")
    @WebResult(name = "consultarHC2Return", targetNamespace = "http://ws.hc2.dc.com/v1")
    public java.lang.String consultarHC2(
        @WebParam(name = "solicitud", targetNamespace = "http://ws.hc2.dc.com/v1")
        com.dc.hc2.ws.v1.SolicitudPlus solicitud
    ) throws HC2PNJException;
}
