
package co.com.datacredito.services.serviciohistoriacreditoplus.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2019-12-09T18:06:19.042+01:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "Fault", targetNamespace = "http://ws.hc2.dc.com/v1")
public class HC2PNJException extends Exception {
    
    private com.dc.hc2.ws.v1.Fault fault;

    public HC2PNJException() {
        super();
    }
    
    public HC2PNJException(String message) {
        super(message);
    }
    
    public HC2PNJException(String message, Throwable cause) {
        super(message, cause);
    }

    public HC2PNJException(String message, com.dc.hc2.ws.v1.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public HC2PNJException(String message, com.dc.hc2.ws.v1.Fault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.dc.hc2.ws.v1.Fault getFaultInfo() {
        return this.fault;
    }
}
