operaciones:
  api:
    urlBase: https://demo-servicesesb.datacredito.com.co
    evidenteProperties:
      urlEvidente: /wss/idws2/services/ServicioIdentificacionPlus
      idUsuarioEntidad: ODAwODkyMzA=
      paramProducto: 3136
      producto: 010
      canal: 001
security:
  trustStore: C:/clientes/prueba/demo-servicesesb.jks
  trustStorePassword: experian
  keyStore: C:/clientes/prueba/demo-servicesesb.jks
  keyStorePassword: experian
  allowInsecureParser: 1
  certPassword: experian
  password: experian
  user: 2-830513238
  signaturePropertyFile: dev/crypto.properties
  signatureUser: experian.sign
  mustUnderstand: false
  signatureParts: "{Content}{http://schemas.xmlsoap.org/soap/envelope/}Body;{Element}{http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd}UsernameToken;{Element}{http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd}Timestamp;"
  signatureKeyId: DirectReference
  signatureAlgorithm: http://www.w3.org/2000/09/xmldsig#rsa-sha1

server:
  servlet:
    context-path: /experian-rest
  port: 5000